### PR TITLE
Enabled circuit configuration - assuming v0.0.22 for next PyVicare package

### PR DESCRIPTION
**Pull request by vandenberghev**
All changes from oischinger/ha_vicare master branch pre-merged

### CODE REVIEW

**Comment by vandenberghev** [comment]
Tested & working.

Beware! Config needs an update.
Example config:

```
- platform: vicare
  username: !secret viessmann_username
  password: !secret viessmann_password
  circuit: 1
```

**Comment by oischinger** [comment]
Looks good but let's wait for the PyVicare update

**Comment by vandenberghev** [comment]
PyViCare 0.0.30 has been released --> updated version requirement

**Comment by killtux** [comment]
how has the config to look like if you want to display 2 circuits?

**Comment by oischinger** [comment]
Unfortunately that's not possible at the moment.

**Pull request merged**
