### PR TITLE
Add DHCP discovery config for Viessmann integration

### PR DESCRIPTION
**Pull request by woehrl01**
This PR adds the [DHCP discovery configuration](https://developers.home-assistant.io/docs/creating_integration_manifest/#dhcp) for Viessmann Devices to the manifest. This can be used in combination with PR #43 to jump into the correct config flow for adding new devices.

### CODE REVIEW

**Comment by woehrl01** [comment]
The tests are correctly failing currently with "DHCP information in a manifest requires a config flow to exist" as #43 is not yet merged to master.

**Comment by oischinger** [comment]
Good idea, haven't even thought of MAC address discovery.
The manifest entry itself doesn't seem to do anything it seems. I believe I have to implement an additional dhcp discover config flow for this to work. I'll play around with that.

**Comment by woehrl01** [comment]
To my understanding, the manifest entry triggers the DHCP discovery flow when implemented.

**Comment by oischinger** [comment]
I moved your commit over to  #43. If you don't mind I'll close this PR?

**Pull request closed without merging**
